### ISSUE TITLE
Reading group papers list inclusion (enhancement req)

### ISSUE THREAD

**Issue by mayukhdas** [boost-starai/boost-starai.github.io#65]
# ENHANCEMENT REQUEST
Dear Developers,

Based on our plan to create a reading group page, I would like to open a discussion regarding whether 
* The reading group papers should be posted as a list on a separate page? OR
* Should it be posted in "Blog" under a new "category" say "Reading Group papers"? 

Since this is design consideration, I believe we should discuss before I start doing something.

Thanks
--Mayukh

**Comment by hayesall** [comment]
"Blog" seems pretty appropriate for reading group info, since Reading Group requires weekly updates.

It's a little off-topic, but the current versions of "Blog" and "Projects" might be more appropriate as a single page.

We might consider storing a .csv of reading group data on Gists and load in the last 10 weeks or so with JavaScript. Some sort of visualization for papers would be amazing, like a D3 graph where each node is a paper and edges represent common authors between papers from reading group.

**Comment by mayukhdas** [comment]
Okay. So populating a list in a new **category** in blog seems appropriate.

Visualization is a good idea. However, it may take time in building it. For now it is better to get the list out as a blog roll.

This is my opinion. The professor should be the right person to finalize.

**Comment by boost-starai** [comment]
Let us discuss this and decide. Please make sure that the blog is only objective and does not have any subjective opinions, particularly if it is associated with our code.

SN

**Comment by mayukhdas** [comment]
Professor,

The Blog presently displays only posts categorized as *'research highlights'*. So, the proposition is to create a new category inside the Blog  (Ex: 'Reading Group') and update each week's reading group paper as a new blog post in that category instead of creating a separate page in the website. Such a change with cause the Blog page to display just a lot more posts, which will be divided into 2 categories by appropriate sub-headings (reading group papers will come under Reading group sub-heading).

But, that is just a thought. As you mentioned and we also are of the same opinion that we need to discuss with you before moving ahead.  

Thanks and Regards
Mayukh

**Comment by harshakokel** [comment]
For the upcoming fall course, we are planning to publish the reading list on the website. However,  updating the code, giving a build and publishing it on the server on a weekly basis for small modification might not be the best way during the semester. I suggested @athresh to embed a   google document on the starling website as a webpage, that way we get the best of both worlds: easy updates and a post on the webpage. This would be hopefully a user-friendly and secure way.
