### ISSUE TITLE
Communicating with computers sub-project page showing wrong text

### ISSUE THREAD

**Issue by mayukhdas** [boost-starai/boost-starai.github.io#77]
Communicating with computers sub project page showing wrong text  (the one before the recent changes)

It was showing the correct text till last night. What happened??
Overwritten by some merge???

https://starling.utdallas.edu/projects/communicating-with-computers/

![image](https://user-images.githubusercontent.com/7583618/46096291-6fc7a980-c184-11e8-868b-5d3d69c7f0c6.png)

**Comment by harshakokel** [comment]
Fixed with following pull request.

https://github.com/starling-lab/starling.utdallas.edu/pull/76

**Comment by hayesall** [comment]
Merged into default branch at #78, marking issue as resolved.
