### ISSUE TITLE
Is the 2018 Ramanan et al. KR paper supposed to be listed twice?

### ISSUE THREAD

**Issue by hayesall** [boost-starai/boost-starai.github.io#92]
Issues regarding how the website `starling.utdallas.edu` is displayed must include:

* [X] Operating System: Fedora Linux 28
* [X] Web Browser & Version: Chrome 
* [X] Screenshots (if appropriate)

---

Screenshot below, reference in question is highlighted.

![screenshot](https://user-images.githubusercontent.com/11916674/46911465-3cc23b80-cf22-11e8-8f49-0b2e42941c0f.png)

**Comment by sridas123** [comment]
One entry is for the KR conference and another for the workshop at KR, and the paper name is the same. Hence, I guess this is not an issue.

**Comment by hayesall** [comment]
Gotcha, my bad. I think the only other time this happened was with the 2006/2007 versions of *A Decision Theoretic Model of Assistance* (where the title was the same between workshop and conference).

I'll close out the issue but we might revisit this in the future: both point to the same arXiv link, and two versions of the same paper might make for slightly odd bibliometrics down the road.
